version: "3.8"

services:
  dontar_demo:
    build: ./demo
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:mysql://clinica_dontar:3306/clinica_odontologica?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: Camila
      DB_PASSWORD: Camila38944251
      JWT_SECRET: very_long_secret_key_that_has_more_than_32_bytes_for_security_purposes
    restart: always
    depends_on:
      clinica_dontar:
        condition: service_healthy

  clinica_dontar:
    image: mysql:8.0.23
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Camila38944251
      MYSQL_USER: Camila
      MYSQL_PASSWORD: Camila38944251
      MYSQL_DATABASE: clinica_odontologica
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s



