version: "3.8"

services:
  dontar_demo:
    build: ./demo
    ports:
      - "8081:8081"
    env_file:
      - .env
    restart: always
    depends_on:
      clinica_dontar:
        condition: service_healthy

  clinica_dontar:
    image: mysql:8.0.23
    ports:
      - "3307:3306"
    env_file:
      - .env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s





