# Nombre de la aplicacion
spring.application.name=dontar_demo

# Configuracion de la base de datos MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT
jwt.secret=${JWT_SECRET}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=${PORT}
server.address=0.0.0.0


# Dev
spring.devtools.restart.enabled=true

spring.messages.basename=messages



